### ISSUE TITLE
Didn't work with Tapermonkey.

### ISSUE THREAD

**Issue by Raijin-MK** [k-aito/userscripts#1]
Is it possible to solve the problem with Tapermonkey or do I have to go through violentmonkey ?

**Comment by k-aito** [comment]
Hello @Raijin-MK 

Can you give a try with this version https://github.com/k-aito/userscripts/blob/958c199a29fc90ef2eb043a833929dde2836e74e/compare-amazon-prices.user.js in my test it looks like it was working.

**Comment by k-aito** [comment]
I will merge if it doesn't help, you can reopen the issue.
